### ISSUE TITLE
[Feature Request]: Integrate WindowsFormsCalendar Control into Krypton Standard?

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Extended-Toolkit#236]
Hey @Wagnerp, @Smurf-IV,

is it possible to integrate the WindowsFormsCalendar-Control into Krypton so the colour themes for example will apply?

Located under:
https://www.codeproject.com/Articles/38699/A-Professional-Calendar-Agenda-View-That-You-Will

Forked versions I founded:
https://github.com/derekantrican/Winforms-Calendar
https://github.com/Opzet/Winforms-Calendar

Blue Style is okay:
![grafik](https://user-images.githubusercontent.com/32876506/128629531-c8d1f50b-dffc-454f-8d63-4a1282eb5a42.png)

But a Dark-Style... :(
![grafik](https://user-images.githubusercontent.com/32876506/128629543-a2ad3464-dfed-4e30-811b-fc770a811b00.png)

Greetings from Germany,
Danny

**Comment by Smurf-IV** [comment]
Sorry but no to this - as the license is "The GNU Lesser General Public License (LGPLv3)"
Which means all code that uses the dll "could" also need to be shipped in the `clear` - which does not fit most companies usage of code.

Yes I understand about the "L" part, but some companies just state "NO"

**Comment by DarthVader85PA** [comment]
Too bad. Nevertheless many thanks.

**Comment by DarthVader85PA** [comment]
But is there a way, that you create a control like this? Or is it very defficult?

**Comment by Smurf-IV** [comment]
Of course it's possible, but the problems will be with the Drag Drop regions and the colouring of these regions when a different theme is used, so that they still "Show up" against the background.

It might be made easier with the charting controls available in later .Net frameworks, but then how to make it compatible with Krypton for net < 4.5 would be a problem, and I'm not sure those charting controls are even in core ??
